services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-nginx
    restart: always
    depends_on:
      - wordpress
    expose:
      - '80'
      - '443'
      - '8080'

    # ports:
    #   - '80:80'

    volumes:
      - nginx/logs:/var/log/nginx
      - ./wordpress:/var/www/html:rw

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    # depends_on:
    #   - redis

    expose:
      - '9000'

    # ports:
    #   - '9000:80'

    environment:
      # - SERVICE_FQDN_WORDPRESS
      ENVIRONMENT: ${ENVIRONMENT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      WORDPRESS_TABLE_PREFIX: ${WP_DB_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}

    # privileged: true
    volumes:
      - ./wordpress:/var/www/html:rw

  # adminer:
  #   image: adminer:latest
  #   container_name: ${APP_NAME}-adminer
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   expose:
  #     - '8080'

  #   ports:
  #     - '8080:8080'
# volumes:
#   nginx_logs:
#   wordpress-files:
#   # mariadb-data:
#   redis:
