services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-nginx
    restart: always
    depends_on:
      - wordpress
    expose:
      - '80'
      - '443'
      - '8080'

    # ports:
    #   - '80:80'

    volumes:
      - nginx/logs:/var/log/nginx
      - wordpress-files:/var/www/html:rw

  wordpress:
    user: '33:33'
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always

    expose:
      - '9000'

    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      WORDPRESS_TABLE_PREFIX: ${WP_DB_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}

    volumes:
      - wordpress-files:/var/www/html:rw
