<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Carbon_Fields_Yoast\\' => array($vendorDir . '/htmlburger/carbon-fields-yoast/core'),
);
