<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0b3ce319894563b1071503890745dd88
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Carbon_Fields_Yoast\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Carbon_Fields_Yoast\\' => 
        array (
            0 => __DIR__ . '/..' . '/htmlburger/carbon-fields-yoast/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0b3ce319894563b1071503890745dd88::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0b3ce319894563b1071503890745dd88::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0b3ce319894563b1071503890745dd88::$classMap;

        }, null, ClassLoader::class);
    }
}
